name: Lint to the Future Dashboard

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wozny1989/lttf-dashboard@4af641df699bb28e9fd5f222f48c02b7585c0d21
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          node-version: '20'
